version: '12'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=qwerty123456

